# Site Settings
title: Data Science Portfolio
email: your-email@example.com
description: A showcase of my Altair visualizations hosted on GitHub.

# URL Settings
# If your site is at username.github.io/my-repo/, set baseurl to /my-repo
baseurl: "" 
url: "https://username.github.io"

# Build Settings
markdown: kramdown
theme: minima
include: [charts] # This tells GitHub to include your HTML charts folder