title: Visualizing Global Earthquakes - Understanding Global Earthquake Behaviours and Patterns
email:
description: 

baseurl: "/VisualizingGlobalEarthquakes"
url: "https://username.github.io"

markdown: kramdown
theme: minima
include: [charts]